server.port: 5050
spring:
  application.name: 'admin-service'
  boot:
    admin:
      ui:
        available-languages: english
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
        service-labels:
          spring-boot: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true